project:
  type: website
  output-dir: docs

website:
  title: "Jameson_DevOps_for_DataScience"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - eda.qmd
      - model.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto